export const APOSTROPHE = '\u02bc';
export const TURNED_COMMA = '\u2018';

export const LATIN_CHARACTERS = {
  ['A']: 'А',
  ['a']: 'а',
  ['B']: 'Б',
  ['b']: 'б',
  ['D']: 'Д',
  ['d']: 'д',
  ['E']: 'Е',
  ['e']: 'е',
  ['F']: 'Ф',
  ['f']: 'ф',
  ['G']: 'Г',
  ['g']: 'г',
  ['H']: 'Ҳ',
  ['h']: 'ҳ',
  ['I']: 'И',
  ['i']: 'и',
  ['J']: 'Ж',
  ['j']: 'ж',
  ['K']: 'К',
  ['k']: 'к',
  ['L']: 'Л',
  ['l']: 'л',
  ['M']: 'М',
  ['m']: 'м',
  ['N']: 'Н',
  ['n']: 'н',
  ['O']: 'О',
  ['o']: 'о',
  ['P']: 'П',
  ['p']: 'п',
  ['Q']: 'Қ',
  ['q']: 'қ',
  ['R']: 'Р',
  ['r']: 'р',
  ['S']: 'С',
  ['s']: 'с',
  ['T']: 'Т',
  ['t']: 'т',
  ['U']: 'У',
  ['u']: 'у',
  ['V']: 'В',
  ['v']: 'в',
  ['X']: 'Х',
  ['x']: 'х',
  ['Y']: 'Й',
  ['y']: 'й',
  ['Z']: 'З',
  ['z']: 'з',
} as const;

export type LATIN_CHARACTER = keyof typeof LATIN_CHARACTERS;

export const CYRILLIC_CHARACTERS = {
  ['А']: 'A',
  ['а']: 'a',
  ['Б']: 'B',
  ['б']: 'b',
  ['Д']: 'D',
  ['д']: 'd',
  ['Е']: 'E',
  ['е']: 'e',
  ['Ф']: 'F',
  ['ф']: 'f',
  ['Г']: 'G',
  ['г']: 'g',
  ['Ҳ']: 'H',
  ['ҳ']: 'h',
  ['И']: 'I',
  ['и']: 'i',
  ['Ж']: 'J',
  ['ж']: 'j',
  ['К']: 'K',
  ['к']: 'k',
  ['Л']: 'L',
  ['л']: 'l',
  ['М']: 'M',
  ['м']: 'm',
  ['Н']: 'N',
  ['н']: 'n',
  ['О']: 'O',
  ['о']: 'o',
  ['П']: 'P',
  ['п']: 'p',
  ['Қ']: 'Q',
  ['қ']: 'q',
  ['Р']: 'R',
  ['р']: 'r',
  ['С']: 'S',
  ['с']: 's',
  ['Т']: 'T',
  ['т']: 't',
  ['У']: 'U',
  ['у']: 'u',
  ['В']: 'V',
  ['в']: 'v',
  ['Х']: 'X',
  ['х']: 'x',
  ['Й']: 'Y',
  ['й']: 'y',
  ['З']: 'Z',
  ['з']: 'z',
  ['Ў']: `O${TURNED_COMMA}`,
  ['ў']: `o${TURNED_COMMA}`,
  ['Ғ']: `G${TURNED_COMMA}`,
  ['ғ']: `g${TURNED_COMMA}`,
  ['Ш']: 'Sh',
  ['ш']: 'sh',
  ['Ч']: 'Ch',
  ['ч']: 'ch',
  ['Ё']: 'Yo',
  ['ё']: 'yo',
  ['Ц']: 'S',
  ['ц']: 's',
  ['Ь']: '',
  ['ь']: '',
  ['Э']: 'E',
  ['э']: 'e',
  ['Ю']: 'Yu',
  ['ю']: 'yu',
  ['Я']: 'Ya',
  ['я']: 'ya',
  ['Ъ']: APOSTROPHE,
  ['ъ']: APOSTROPHE,
} as const;

export type CYRILLIC_CHARACTER = keyof typeof CYRILLIC_CHARACTERS;

export const CYRILLIC_LETTER = `\u0400-\u04FF`;
export const CYRILLIC_VOVEL = `аоэеиуўёюя`;

export const LATIN_LETTER = `a-z`;
export const LATIN_VOVEL = `aeiou`;
